#!/usr/bin/python
# coding: utf-8

import sys
from pypdf2xml import pdf2xml

if len(sys.argv) != 2:
    print """usage:
to see the output:
\tpdf2xml file.pdf
to write output to file:
\tpdf2xml file.pdf > outfile.xml
"""
else:
    print pdf2xml(open(sys.argv[1],'rb'))


